USE [master]
GO

/****** Object:  Database [FSE_ProjectManager]    Script Date: 2/12/2019 4:24:45 PM ******/
CREATE DATABASE [FSE_ProjectManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FSE_ProjectManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FSE_ProjectManager.mdf' , SIZE = 6100KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FSE_ProjectManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FSE_ProjectManager_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FSE_ProjectManager] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FSE_ProjectManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FSE_ProjectManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FSE_ProjectManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FSE_ProjectManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FSE_ProjectManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FSE_ProjectManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FSE_ProjectManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET RECOVERY FULL 
GO

ALTER DATABASE [FSE_ProjectManager] SET  MULTI_USER 
GO

ALTER DATABASE [FSE_ProjectManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FSE_ProjectManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FSE_ProjectManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FSE_ProjectManager] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FSE_ProjectManager] SET  READ_WRITE 
GO


